UI_TEXT = {
    "en": {
        "title": "AI Startup Analyst - Interview Phase",
        "questions": [
            {"question": "What is your startup idea and what specific problem does it solve?", "guide": "Example: 'We are building an autonomous accounting SaaS for SMBs focusing on ledger reconciliation...'"},
            {"question": "Who is your exact target niche market and user base initially?", "guide": "Example: 'Our initial target is dental clinics in the US with 1-5 practitioners...'"},
            {"question": "Who are your 2-3 biggest competitors currently trying to solve this problem, and how will you differentiate?", "guide": "Example: 'We compete with X and Y. We differentiate by having 10x faster integrations using our custom proxy API...'"},
            {"question": "How do you plan to make money from this startup? (SaaS, commission, marketplace, etc.)", "guide": "Example: 'B2B SaaS with a tiered pricing model starting at $199/month...'"},
            {"question": "If you wanted to test this product as quickly and cheaply as possible (without coding or with minimal code), what would be the first core feature you'd offer?", "guide": "Example: 'A simple dashboard that syncs Stripe transactions and flags anomalies...'"}
        ],
        "success_saved": "Thank you! Your data has been saved. Analysis agents are ready to run.",
        "btn_market": "📊 Start Market Analysis",
        "btn_finance": "💰 Start Financial Analysis",
        "btn_mvp": "🚀 Generate MVP Roadmap",
        "btn_synthesis": "🧠 Synthesize All",
        "btn_pdf": "📄 Export VC Report",
        "spin_market": "Conducting market research on the internet...",
        "spin_finance": "Modeling financial data...",
        "spin_mvp": "Creating MVP strategy...",
        "spin_synthesis": "Synthesizing cross-agent insights...",
        "market_dashboard": "📊 Market Analysis Dashboard",
        "market_unknown": "Unknown",
        "market_uptrend": "Uptrend",
        "market_density_red": "**WARNING:** This market is quite congested and highly competitive (Red Ocean). You must carefully define your entry strategy.\n\n_Detail: {}_",
        "market_density_blue": "**OPPORTUNITY:** This market has low competition (Blue Ocean). You can leverage the first-mover advantage.\n\n_Detail: {}_",
        "market_density_info": "**Market Density:** {}",
        "market_funnel_title": "Market Size Funnel Analysis",
        "market_note": "### 📝 Analyst Note",
        "market_metrics_hdr": "### 📐 Market Metrics",
        "market_source": "🔍 Source / Assumption",
        "market_comp_hdr": "### ⚔️ Competitor Intelligence",
        "market_comp_weakness": "**Structural Weakness:**",
        "market_comp_window": "**Exploit Window:**",
        "market_reg_hdr": "### ⚖️ Regulatory Risks",
        "market_reg_impact": "**Impact:**",
        "market_reg_mitigation": "**Mitigation:**",
        "market_unit_economics": "### 💰 Unit Economics",
        "market_model_type": "**Model Type:** {}",
        "market_moat": "### 🏰 Moat Analysis",
        "market_replication": "Replication Difficulty (1-10)",
        "market_choke": "### ⚠️ 18-Month Kill Scenarios",
        "market_kill_scenario": "**Kill Scenario #{}:** {}",
        "finance_dashboard": "💰 Financial Analysis Results",
        "finance_score": "Investment Score",
        "finance_ltv_cac": "LTV/CAC Estimate",
        "finance_capital": "Capital Intensity",
        "finance_ltv_comment": "**LTV/CAC Comment:** {}",
        "finance_capital_detail": "**Capital Requirement Detail:** {}",
        "finance_burn_rate": "**Estimated Monthly Burn Rate:** {}",
        "finance_score_justification": "**Score Justification:** {}",
        "finance_red_flags": "### 🚩 Red Flags & Risks",
        "finance_death_scenario": "### 💀 Death Scenario",
        "mvp_dashboard": "🚀 MVP Roadmap & Founder Sprint",
        "mvp_complexity": "**Complexity Score:** `{}`",
        "mvp_time_to_market": "**⏳ Estimated Time-to-Market:** `{}`",
        "mvp_focus": "### ✅ Focus Features (Day-1)",
        "mvp_cut": "### ❌ Cut Features (For Now)",
        "mvp_tech": "### 🛠️ Tech & Tool Recommendations",
        "mvp_build_buy": "### 🛒 Build vs. Buy Decisions",
        "mvp_sprint": "### 📅 Founder Sprint (To-Do List)",
        "mvp_week0": "### 🧪 Week 0 Validation Task",
        "mvp_pivot": "### 🔄 Pivot Trigger",
        "chat_placeholder": "Type your answer here...",
        "answer_too_short": "This answer is too brief for a proper VC-grade analysis. Please provide more concrete strategy details.",
        "analysis_locked": "Complete the interview with substantive answers to unlock analysis.",
        "submit_answers": "Submit Answers",
        "run_analysis": "Run Analysis",
        "synthesis_dashboard": "🧠 Cross-Agent Synthesis",
        "synthesis_contradiction": "**Biggest Contradiction:** {}",
        "synthesis_signal": "**Strongest Signal:** {}",
        "synthesis_critical_path": "### 🎯 Critical Path (Next 3 Steps)",
        "vc_summary": "🎯 VC Investment Intelligence Summary",
        "vc_verdict_strong": "🟢 FUNDABLE — Strong investment candidate",
        "vc_verdict_conditional": "🟡 CONDITIONAL — Needs specific improvements before funding",
        "vc_verdict_weak": "🔴 NOT FUNDABLE — Fundamental issues must be resolved",
        "pdf_success": "PDF generated successfully!",
        "data_sources": "🔍 Data Sources & Confidence Level",
        "market_sources": "Search corpus: {} characters from {} queries",
        "market_sources_warn": "⚠️ Limited web data found. Market figures are model estimates, not real-time data.",
        "finance_sources": "Analysis date: {}"
    },
    "tr": {
        "title": "AI Startup Analisti - Mülakat Aşaması",
        "questions": [
            {"question": "Startup fikriniz nedir ve hangi spesifik problemi çözüyor?", "guide": "Örnek: 'KOBİ'ler için otonom muhasebe SaaS'ı geliştiriyoruz, defter mutabakatına odaklanıyoruz...'"},
            {"question": "İlk etapta hedeflediğiniz niş pazar ve kullanıcı kitlesi tam olarak kimler?", "guide": "Örnek: 'İlk hedef kitlemiz, Türkiye'deki 1-5 hekimli diş klinikleridir...'"},
            {"question": "Şu an bu problemi çözmeye çalışan en büyük 2-3 rakibiniz kim ve siz onlardan nasıl farklılaşacaksınız?", "guide": "Örnek: 'X ve Y ile rekabet ediyoruz. Farkımız, API'mizin 10 kat daha hızlı entegre olabilmesi...'"},
            {"question": "Bu girişimden nasıl para kazanmayı planlıyorsunuz? (SaaS, komisyon, pazaryeri vb.)", "guide": "Örnek: 'Aylık 199$ başlangıç fiyatlı B2B SaaS modeliyle...'"},
            {"question": "Bu ürünü en hızlı ve en ucuz şekilde (kodlamadan veya minimal kodla) test etmek isteseniz, sunacağınız ilk temel özellik ne olurdu?", "guide": "Örnek: 'Sadece Stripe işlemlerini senkronize edip anormallikleri işaretleyen basit bir panel...'"}
        ],
        "success_saved": "Teşekkürler! Verileriniz kaydedildi. Analiz ajanları çalışmaya hazır.",
        "btn_market": "📊 Pazar Analizini Başlat",
        "btn_finance": "💰 Finansal Analizi Başlat",
        "btn_mvp": "🚀 MVP Yol Haritasını Çıkar",
        "btn_synthesis": "🧠 Tümünü Sentezle",
        "btn_pdf": "📄 VC Raporunu Dışa Aktar",
        "spin_market": "İnternette pazar araştırması yapılıyor...",
        "spin_finance": "Finansal veriler modelleniyor...",
        "spin_mvp": "MVP stratejisi oluşturuluyor...",
        "spin_synthesis": "Ajan içgörüleri sentezleniyor...",
        "market_dashboard": "📊 Pazar Analizi Dashboard",
        "market_unknown": "Bilinmiyor",
        "market_uptrend": "Yükseliş Trendi",
        "market_density_red": "**DİKKAT:** Bu pazar oldukça sıkışık ve rekabet yüksek (Kırmızı Okyanus). Giriş stratejinizi çok iyi belirlemelisiniz.\n\n_Detay: {}_",
        "market_density_blue": "**FIRSAT:** Bu pazar düşük rekabet barındırıyor (Mavi Okyanus). İlk hamle avantajını kullanabilirsiniz.\n\n_Detay: {}_",
        "market_density_info": "**Pazar Yoğunluğu:** {}",
        "market_funnel_title": "Pazar Büyüklüğü Huni (Funnel) Analizi",
        "market_note": "### 📝 Analist Notu",
        "market_metrics_hdr": "### 📐 Pazar Metrikleri",
        "market_source": "🔍 Kaynak / Varsayım",
        "market_comp_hdr": "### ⚔️ Rakip İstihbarat Analizi",
        "market_comp_weakness": "**Yapısal Zayıflık:**",
        "market_comp_window": "**Fırsat Penceresi:**",
        "market_reg_hdr": "### ⚖️ Düzenleyici Riskler",
        "market_reg_impact": "**Etki:**",
        "market_reg_mitigation": "**Azaltma Stratejisi:**",
        "market_unit_economics": "### 💰 Birim Ekonomisi",
        "market_model_type": "**Model Tipi:** {}",
        "market_moat": "### 🏰 Moat (Savunulabilirlik) Analizi",
        "market_replication": "Kopyalanma Zorluğu (1-10)",
        "market_choke": "### ⚠️ 18 Aylık İflas Senaryoları",
        "market_kill_scenario": "**İflas Senaryosu #{}:** {}",
        "finance_dashboard": "💰 Finansal Analiz Sonuçları",
        "finance_score": "Yatırım Skoru",
        "finance_ltv_cac": "LTV/CAC Tahmini",
        "finance_capital": "Sermaye Yoğunluğu",
        "finance_ltv_comment": "**LTV/CAC Yorumu:** {}",
        "finance_capital_detail": "**Sermaye İhtiyacı Detayı:** {}",
        "finance_burn_rate": "**Tahmini Aylık Nakit Yakımı (Burn Rate):** {}",
        "finance_score_justification": "**Skor Gerekçesi:** {}",
        "finance_red_flags": "### 🚩 Kırmızı Bayraklar & Riskler",
        "finance_death_scenario": "### 💀 Ölüm Senaryosu",
        "mvp_dashboard": "🚀 MVP Yol Haritası & Kurucu Sprinti",
        "mvp_complexity": "**Karmaşıklık Skoru:** `{}`",
        "mvp_time_to_market": "**⏳ Tahmini Pazara Çıkış Süresi:** `{}`",
        "mvp_focus": "### ✅ Odaklanılacak Özellikler (Day-1)",
        "mvp_cut": "### ❌ Elenen Özellikler (Şimdilik)",
        "mvp_tech": "### 🛠️ Teknoloji & Araç Önerileri",
        "mvp_build_buy": "### 🛒 Yap veya Satın Al (Build vs Buy)",
        "mvp_sprint": "### 📅 Kurucu Sprinti (To-Do List)",
        "mvp_week0": "### 🧪 0. Hafta Doğrulama Görevi",
        "mvp_pivot": "### 🔄 Pivot Tetikleyicisi",
        "chat_placeholder": "Cevabınızı buraya yazın...",
        "answer_too_short": "Bu cevap profesyonel bir analiz için çok yüzeysel. Lütfen stratejiniz hakkında daha somut detaylar verin.",
        "analysis_locked": "Analizi açmak için tüm soruları yeterli detayla yanıtlayın.",
        "submit_answers": "Cevapları Gönder",
        "run_analysis": "Analizi Başlat",
        "synthesis_dashboard": "🧠 Çapraz Ajan Sentezi",
        "synthesis_contradiction": "**En Büyük Çelişki:** {}",
        "synthesis_signal": "**En Güçlü Sinyal:** {}",
        "synthesis_critical_path": "### 🎯 Kritik Yol (Sonraki 3 Adım)",
        "vc_summary": "🎯 VC Yatırım İstihbarat Özeti",
        "vc_verdict_strong": "🟢 YATIRIM YAPILABİLİR — Güçlü yatırım adayı",
        "vc_verdict_conditional": "🟡 KOŞULLU — Fonlama öncesi spesifik iyileştirmeler gerekli",
        "vc_verdict_weak": "🔴 YATIRIM YAPILAMAZ — Temel sorunların çözülmesi şart",
        "pdf_success": "PDF başarıyla oluşturuldu!",
        "data_sources": "🔍 Veri Kaynakları & Güvenilirlik Seviyesi",
        "market_sources": "Arama korpusu: {} sorgudan {} karakter",
        "market_sources_warn": "⚠️ Sınırlı web verisi bulundu. Pazar rakamları gerçek zamanlı veri değil, model tahminleridir.",
        "finance_sources": "Analiz tarihi: {}"
    }
}
